### PR TITLE
#11 Add support for PackageReference Update

### PR DESCRIPTION
**Pull request by jaboc83**

### CODE REVIEW

**Comment by stevedesmond-ca** [comment]
Hi Jake, thanks for the PR! Things are looking pretty good, but I'm seeing a lot of whitespace changes -- could you try to keep things more in line with the existing formatting, to limit the diff?

**Comment by jaboc83** [comment]
Ah, yeah my bad. I must have left my auto formatter on and had the ignore whitespace on in the git diff. I'll undo the whitespace changes and resubmit this and the other PR

**Comment by stevedesmond-ca** [comment]
Rebased to master in b87ca1d

**Comment by stevedesmond-ca** [comment]
Thanks again!

**Pull request closed without merging**
